// build-landing.mjs — precompile the marketing landing's JSX into one minified
// bundle so the browser doesn't ship @babel/standalone and compile 11 files at
// runtime. Each file keeps the existing globals architecture (it reads/writes
// window.*), so we transform JSX -> JS, wrap each file in its own IIFE to keep
// top-level `const { useState } = React` declarations from colliding, then
// concatenate in the same order index.html used to load them.
//
// Run by `npm run build` (prebuild) and manually before previewing the landing.

import { build } from 'esbuild';
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SRC = join(__dirname, '..', 'public', 'landing', 'src');
const OUT = join(SRC, 'app.bundle.js');

// Same order the old <script type="text/babel"> tags used. Order matters:
// each file Object.assign(window, {...}) exports; later files read those globals.
const FILES = [
  'hooks.jsx',
  'phone-screens.jsx',
  'chrome.jsx',
  'hero.jsx',
  'manifesto-film.jsx',
  'features.jsx',
  'regions.jsx',
  'marquee-ai.jsx',
  'leaderboard-trust.jsx',
  'faq-final.jsx',
  'app.jsx',
];

const parts = [];
for (const name of FILES) {
  const code = await readFile(join(SRC, name), 'utf8');
  // Transform JSX -> React.createElement (classic runtime, global React),
  // bundled+minified per file. Wrapping in an IIFE isolates each file's
  // top-level declarations exactly like babel-standalone did at runtime.
  const result = await build({
    stdin: { contents: code, loader: 'jsx', resolveDir: SRC, sourcefile: name },
    bundle: false,
    write: false,
    minify: true,
    format: 'iife',          // wraps output in (() => { ... })();
    jsx: 'transform',
    jsxFactory: 'React.createElement',
    jsxFragment: 'React.Fragment',
    target: ['es2019'],
  });
  parts.push(`/* ${name} */\n${result.outputFiles[0].text}`);
}

const banner = '/* BFU landing — precompiled bundle. Source: public/landing/src/*.jsx. Regenerated by scripts/build-landing.mjs. */\n';
await writeFile(OUT, banner + parts.join('\n'), 'utf8');

const bytes = Buffer.byteLength(banner + parts.join('\n'));
console.log(`build-landing: wrote ${OUT} (${(bytes / 1024).toFixed(1)} KB, ${FILES.length} files)`);
